package decok.dfcdvadstf.catframe.datagen.migration.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonParser;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Auto-generated by .qoder/extract_datagen.py - do not edit.
 * <p>
 * Raw JSON of every hand-written models/item file (266).
 * <p>
 * 由 .qoder/extract_datagen.py 自动生成，请勿手改。
 */
public final class ModelItemRawData {

    private static final Map<String, String> RAW = new LinkedHashMap<String, String>();

    static {
        RAW.put("item/acacia_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_acacia\"}}");
        RAW.put("item/activator_rail", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/rail_activator\"}}");
        RAW.put("item/air", "{}");
        RAW.put("item/allium", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_allium\"}}");
        RAW.put("item/apple", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/apple\"}}");
        RAW.put("item/arrow", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/arrow\"}}");
        RAW.put("item/baked_potato", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potato_baked\"}}");
        RAW.put("item/bed", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bed\"}}");
        RAW.put("item/beef", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/beef_raw\"}}");
        RAW.put("item/birch_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_birch\"}}");
        RAW.put("item/black_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_black\"}}");
        RAW.put("item/blaze_powder", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/blaze_powder\"}}");
        RAW.put("item/blaze_rod", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/blaze_rod\"}}");
        RAW.put("item/blue_orchid", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_blue_orchid\"}}");
        RAW.put("item/blue_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_blue\"}}");
        RAW.put("item/boat", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/boat\"}}");
        RAW.put("item/bone", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bone\"}}");
        RAW.put("item/bone_meal", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bone_meal\"}}");
        RAW.put("item/book", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/book_normal\"}}");
        RAW.put("item/book_and_quill", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/book_writable\"}}");
        RAW.put("item/bow", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"items/bow_standby\"},\"display\":{\"thirdperson_righthand\":{\"rotation\":[-80,260,-40],\"translation\":[-1,-2,2.5],\"scale\":[0.9,0.9,0.9]},\"thirdperson_lefthand\":{\"rotation\":[-80,-280,40],\"translation\":[-1,-2,2.5],\"scale\":[0.9,0.9,0.9]},\"firstperson_righthand\":{\"rotation\":[0,-90,25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]},\"firstperson_lefthand\":{\"rotation\":[0,90,-25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]}}}");
        RAW.put("item/bow_pulling_0", "{\"parent\":\"minecraft:item/bow\",\"textures\":{\"layer0\":\"minecraft:items/bow_pulling_0\"}}");
        RAW.put("item/bow_pulling_1", "{\"parent\":\"minecraft:item/bow\",\"textures\":{\"layer0\":\"minecraft:items/bow_pulling_1\"}}");
        RAW.put("item/bow_pulling_2", "{\"parent\":\"minecraft:item/bow\",\"textures\":{\"layer0\":\"minecraft:items/bow_pulling_2\"}}");
        RAW.put("item/bowl", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bowl\"}}");
        RAW.put("item/bread", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bread\"}}");
        RAW.put("item/brewing_stand", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/brewing_stand\"}}");
        RAW.put("item/brick", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/brick\"}}");
        RAW.put("item/brown_mushroom", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/mushroom_brown\"}}");
        RAW.put("item/brown_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_brown\"}}");
        RAW.put("item/bucket", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bucket_empty\"}}");
        RAW.put("item/cake", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/cake\"}}");
        RAW.put("item/carrot", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/carrot\"}}");
        RAW.put("item/carrot_on_a_stick", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/carrot_on_a_stick\"}}");
        RAW.put("item/cauldron", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/cauldron\"}}");
        RAW.put("item/chainmail_boots", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chainmail_boots\"}}");
        RAW.put("item/chainmail_chestplate", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chainmail_chestplate\"}}");
        RAW.put("item/chainmail_helmet", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chainmail_helmet\"}}");
        RAW.put("item/chainmail_leggings", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chainmail_leggings\"}}");
        RAW.put("item/charcoal", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/charcoal\"}}");
        RAW.put("item/chest_minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_chest\"}}");
        RAW.put("item/chicken", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chicken_raw\"}}");
        RAW.put("item/clay_ball", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/clay_ball\"}}");
        RAW.put("item/clock", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/clock\"}}");
        RAW.put("item/coal", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/coal\"}}");
        RAW.put("item/command_block_minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_command_block\"}}");
        RAW.put("item/comparator", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/comparator\"}}");
        RAW.put("item/compass", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/compass\"}}");
        RAW.put("item/cooked_beef", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/beef_cooked\"}}");
        RAW.put("item/cooked_chicken", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/chicken_cooked\"}}");
        RAW.put("item/cooked_fished", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_cod_cooked\"}}");
        RAW.put("item/cooked_porkchop", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/porkchop_cooked\"}}");
        RAW.put("item/cookie", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/cookie\"}}");
        RAW.put("item/creeper_head", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:items/skull_creeper\"}}");
        RAW.put("item/cyan_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_cyan\"}}");
        RAW.put("item/dandelion", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_dandelion\"}}");
        RAW.put("item/dark_oak_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_roofed_oak\"}}");
        RAW.put("item/detector_rail", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/rail_detector\"}}");
        RAW.put("item/diamond", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond\"}}");
        RAW.put("item/diamond_axe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/diamond_axe\"}}");
        RAW.put("item/diamond_boots", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond_boots\"}}");
        RAW.put("item/diamond_chestplate", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond_chestplate\"}}");
        RAW.put("item/diamond_helmet", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond_helmet\"}}");
        RAW.put("item/diamond_hoe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/diamond_hoe\"}}");
        RAW.put("item/diamond_horse_armor", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond_horse_armor\"}}");
        RAW.put("item/diamond_leggings", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/diamond_leggings\"}}");
        RAW.put("item/diamond_pickaxe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/diamond_pickaxe\"}}");
        RAW.put("item/diamond_shovel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/diamond_shovel\"}}");
        RAW.put("item/diamond_sword", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/diamond_sword\"}}");
        RAW.put("item/dragon_breath", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dragon_breath\"}}");
        RAW.put("item/dye_black", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_black\"}}");
        RAW.put("item/dye_blue", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_blue\"}}");
        RAW.put("item/dye_brown", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_brown\"}}");
        RAW.put("item/dye_cyan", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_cyan\"}}");
        RAW.put("item/dye_gray", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_gray\"}}");
        RAW.put("item/dye_green", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_green\"}}");
        RAW.put("item/dye_light_blue", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_light_blue\"}}");
        RAW.put("item/dye_light_gray", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_silver\"}}");
        RAW.put("item/dye_lime", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_lime\"}}");
        RAW.put("item/dye_magenta", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_magenta\"}}");
        RAW.put("item/dye_orange", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_orange\"}}");
        RAW.put("item/dye_pink", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_pink\"}}");
        RAW.put("item/dye_purple", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_purple\"}}");
        RAW.put("item/dye_red", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_red\"}}");
        RAW.put("item/dye_white", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_white\"}}");
        RAW.put("item/dye_yellow", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/dye_powder_yellow\"}}");
        RAW.put("item/egg", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/egg\"}}");
        RAW.put("item/emerald", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/emerald\"}}");
        RAW.put("item/empty_map", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/map_empty\"}}");
        RAW.put("item/enchanted_book", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/book_enchanted\"}}");
        RAW.put("item/ender_eye", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/ender_eye\"}}");
        RAW.put("item/ender_pearl", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/ender_pearl\"}}");
        RAW.put("item/experience_bottle", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/experience_bottle\"}}");
        RAW.put("item/feather", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/feather\"}}");
        RAW.put("item/fermented_spider_eye", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/spider_eye_fermented\"}}");
        RAW.put("item/fern", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/fern\"}}");
        RAW.put("item/filled_map", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/map_filled\"}}");
        RAW.put("item/fire_charge", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fireball\"}}");
        RAW.put("item/firework_charge", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fireworks_charge\",\"layer1\":\"minecraft:items/fireworks_charge_overlay\"}}");
        RAW.put("item/fireworks", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fireworks\"}}");
        RAW.put("item/fish", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_cod_raw\"}}");
        RAW.put("item/fish_clownfish", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_clownfish_raw\"}}");
        RAW.put("item/fish_pufferfish", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_pufferfish_raw\"}}");
        RAW.put("item/fish_salmon_cooked", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_salmon_cooked\"}}");
        RAW.put("item/fish_salmon_raw", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/fish_salmon_raw\"}}");
        RAW.put("item/fishing_rod", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/fishing_rod_uncast\"}}");
        RAW.put("item/fishing_rod_cast", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/fishing_rod_cast\"}}");
        RAW.put("item/flint", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/flint\"}}");
        RAW.put("item/flint_and_steel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/flint_and_steel\"}}");
        RAW.put("item/flower_pot", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/flower_pot\"}}");
        RAW.put("item/furnace_minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_furnace\"}}");
        RAW.put("item/generated", "{\"parent\":\"builtin/generated\",\"gui_light\":\"front\",\"display\":{\"gui\":{\"rotation\":[0,0,0],\"translation\":[0,0,0],\"scale\":[1,1,1]},\"ground\":{\"rotation\":[0,0,0],\"translation\":[0,2,0],\"scale\":[0.5,0.5,0.5]},\"fixed\":{\"rotation\":[0,0,0],\"translation\":[0,0,0],\"scale\":[1,1,1]},\"on_shelf\":{\"rotation\":[0,180,0],\"translation\":[0,0,0],\"scale\":[1,1,1]},\"thirdperson_righthand\":{\"rotation\":[0,0,0],\"translation\":[0,3,1],\"scale\":[0.55,0.55,0.55]},\"firstperson_righthand\":{\"rotation\":[0,-90,25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]},\"firstperson_lefthand\":{\"rotation\":[0,0,0],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]}}}");
        RAW.put("item/ghast_tear", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/ghast_tear\"}}");
        RAW.put("item/glass_bottle", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potion_bottle_empty\"}}");
        RAW.put("item/glass_pane", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass\"}}");
        RAW.put("item/glowstone_dust", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/glowstone_dust\"}}");
        RAW.put("item/gold_ingot", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_ingot\"}}");
        RAW.put("item/gold_nugget", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_nugget\"}}");
        RAW.put("item/golden_apple", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/apple_golden\"}}");
        RAW.put("item/golden_axe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/gold_axe\"}}");
        RAW.put("item/golden_boots", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_boots\"}}");
        RAW.put("item/golden_carrot", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/carrot_golden\"}}");
        RAW.put("item/golden_chestplate", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_chestplate\"}}");
        RAW.put("item/golden_helmet", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_helmet\"}}");
        RAW.put("item/golden_hoe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/gold_hoe\"}}");
        RAW.put("item/golden_horse_armor", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_horse_armor\"}}");
        RAW.put("item/golden_leggings", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gold_leggings\"}}");
        RAW.put("item/golden_pickaxe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/gold_pickaxe\"}}");
        RAW.put("item/golden_rail", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/rail_golden\"}}");
        RAW.put("item/golden_shovel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/gold_shovel\"}}");
        RAW.put("item/golden_sword", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/gold_sword\"}}");
        RAW.put("item/gray_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_gray\"}}");
        RAW.put("item/green_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_green\"}}");
        RAW.put("item/gunpowder", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/gunpowder\"}}");
        RAW.put("item/handheld", "{\"parent\":\"item/generated\",\"display\":{\"thirdperson_righthand\":{\"rotation\":[0,-90,55],\"translation\":[0,4.0,0.5],\"scale\":[0.85,0.85,0.85]},\"thirdperson_lefthand\":{\"rotation\":[0,90,-55],\"translation\":[0,4.0,0.5],\"scale\":[0.85,0.85,0.85]},\"firstperson_righthand\":{\"rotation\":[0,-90,25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]},\"firstperson_lefthand\":{\"rotation\":[0,90,-25],\"translation\":[1.13,3.2,1.13],\"scale\":[0.68,0.68,0.68]}}}");
        RAW.put("item/hopper", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/hopper\"}}");
        RAW.put("item/hopper_minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_hopper\"}}");
        RAW.put("item/houstonia", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_houstonia\"}}");
        RAW.put("item/human_head", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:items/skull_steve\"}}");
        RAW.put("item/iron_axe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/iron_axe\"}}");
        RAW.put("item/iron_bars", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/iron_bars\"}}");
        RAW.put("item/iron_boots", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_boots\"}}");
        RAW.put("item/iron_chestplate", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_chestplate\"}}");
        RAW.put("item/iron_door", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/door_iron\"}}");
        RAW.put("item/iron_helmet", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_helmet\"}}");
        RAW.put("item/iron_hoe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/iron_hoe\"}}");
        RAW.put("item/iron_horse_armor", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_horse_armor\"}}");
        RAW.put("item/iron_ingot", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_ingot\"}}");
        RAW.put("item/iron_leggings", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/iron_leggings\"}}");
        RAW.put("item/iron_pickaxe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/iron_pickaxe\"}}");
        RAW.put("item/iron_shovel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/iron_shovel\"}}");
        RAW.put("item/iron_sword", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/iron_sword\"}}");
        RAW.put("item/item_frame", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/item_frame\"}}");
        RAW.put("item/jungle_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_jungle\"}}");
        RAW.put("item/ladder", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/ladder\"}}");
        RAW.put("item/lava_bucket", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bucket_lava\"}}");
        RAW.put("item/lead", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/lead\"}}");
        RAW.put("item/leather", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/leather\"}}");
        RAW.put("item/leather_boots", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/leather_boots\",\"layer1\":\"minecraft:items/leather_boots_overlay\"}}");
        RAW.put("item/leather_chestplate", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/leather_chestplate\",\"layer1\":\"minecraft:items/leather_chestplate_overlay\"},\"display\":{\"thirdperson_righthand\":{\"rotation\":[-90,0,0],\"translation\":[-2,2,0],\"scale\":[0.625,0.625,0.625]}}}");
        RAW.put("item/leather_helmet", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/leather_helmet\",\"layer1\":\"minecraft:items/leather_helmet_overlay\"},\"display\":{\"thirdperson_righthand\":{\"rotation\":[-90,0,0],\"translation\":[-2,2,0],\"scale\":[0.625,0.625,0.625]}}}");
        RAW.put("item/leather_leggings", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/leather_leggings\",\"layer1\":\"minecraft:items/leather_leggings_overlay\"},\"display\":{\"thirdperson_righthand\":{\"rotation\":[-90,0,0],\"translation\":[-2,2,0],\"scale\":[0.625,0.625,0.625]}}}");
        RAW.put("item/lever", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/lever\"}}");
        RAW.put("item/light_blue_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_light_blue\"}}");
        RAW.put("item/light_gray_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_silver\"}}");
        RAW.put("item/lilac", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_syringa_top\"}}");
        RAW.put("item/lime_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_lime\"}}");
        RAW.put("item/magenta_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_magenta\"}}");
        RAW.put("item/magma_cream", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/magma_cream\"}}");
        RAW.put("item/map", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/map_empty\"}}");
        RAW.put("item/melon", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/melon\"}}");
        RAW.put("item/melon_seeds", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/seeds_melon\"}}");
        RAW.put("item/milk_bucket", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bucket_milk\"}}");
        RAW.put("item/minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_normal\"}}");
        RAW.put("item/mushroom_stew", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/mushroom_stew\"}}");
        RAW.put("item/name_tag", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/name_tag\"}}");
        RAW.put("item/nether_star", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/nether_star\"}}");
        RAW.put("item/nether_wart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/nether_wart\"}}");
        RAW.put("item/netherbrick", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/netherbrick\"}}");
        RAW.put("item/oak_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_oak\"}}");
        RAW.put("item/orange_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_orange\"}}");
        RAW.put("item/oxeye_daisy", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_oxeye_daisy\"}}");
        RAW.put("item/paeonia", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_paeonia_top\"}}");
        RAW.put("item/painting", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/painting\"}}");
        RAW.put("item/paper", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/paper\"}}");
        RAW.put("item/peony", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_paeonia_top\"}}");
        RAW.put("item/pink_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_pink\"}}");
        RAW.put("item/poisonous_potato", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potato_poisonous\"}}");
        RAW.put("item/poppy", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_rose\"}}");
        RAW.put("item/porkchop", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/porkchop_raw\"}}");
        RAW.put("item/potato", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potato\"}}");
        RAW.put("item/potion", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potion_overlay\",\"layer1\":\"minecraft:items/potion_bottle_drinkable\"}}");
        RAW.put("item/powered_repeater", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:block/repeater_on\"}}");
        RAW.put("item/pumpkin_pie", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/pumpkin_pie\"}}");
        RAW.put("item/pumpkin_seeds", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/seeds_pumpkin\"}}");
        RAW.put("item/purple_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_purple\"}}");
        RAW.put("item/quartz", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/quartz\"}}");
        RAW.put("item/rail", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/rail_normal\"}}");
        RAW.put("item/record_11", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_11\"}}");
        RAW.put("item/record_13", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_13\"}}");
        RAW.put("item/record_blocks", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_blocks\"}}");
        RAW.put("item/record_cat", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_cat\"}}");
        RAW.put("item/record_chirp", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_chirp\"}}");
        RAW.put("item/record_far", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_far\"}}");
        RAW.put("item/record_mall", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_mall\"}}");
        RAW.put("item/record_mellohi", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_mellohi\"}}");
        RAW.put("item/record_stal", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_stal\"}}");
        RAW.put("item/record_strad", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_strad\"}}");
        RAW.put("item/record_wait", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_wait\"}}");
        RAW.put("item/record_ward", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/record_ward\"}}");
        RAW.put("item/red_mushroom", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/mushroom_red\"}}");
        RAW.put("item/red_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_red\"}}");
        RAW.put("item/redstone", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/redstone_dust\"}}");
        RAW.put("item/redstone_torch", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/redstone_torch_on\"}}");
        RAW.put("item/reeds", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/reeds\"}}");
        RAW.put("item/repeater", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/repeater\"}}");
        RAW.put("item/rose", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_rose_top\"}}");
        RAW.put("item/rotten_flesh", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/rotten_flesh\"}}");
        RAW.put("item/saddle", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/saddle\"}}");
        RAW.put("item/shears", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/shears\"}}");
        RAW.put("item/short_grass", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/tallgrass\"}}");
        RAW.put("item/sign", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/sign\"}}");
        RAW.put("item/skeleton_head", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:items/skull_skeleton\"}}");
        RAW.put("item/slime_ball", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/slimeball\"}}");
        RAW.put("item/snowball", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/snowball\"}}");
        RAW.put("item/spawn_egg", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/spawn_egg\",\"layer1\":\"minecraft:items/spawn_egg_overlay\"}}");
        RAW.put("item/speckled_melon", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/melon_speckled\"}}");
        RAW.put("item/spectral_arrow", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/spectral_arrow\"}}");
        RAW.put("item/spider_eye", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/spider_eye\"}}");
        RAW.put("item/splash_potion", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/potion_overlay\",\"layer1\":\"minecraft:items/potion_bottle_splash\"}}");
        RAW.put("item/spruce_sapling", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/sapling_spruce\"}}");
        RAW.put("item/stick", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/stick\"}}");
        RAW.put("item/stone_axe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/stone_axe\"}}");
        RAW.put("item/stone_hoe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/stone_hoe\"}}");
        RAW.put("item/stone_pickaxe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/stone_pickaxe\"}}");
        RAW.put("item/stone_shovel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/stone_shovel\"}}");
        RAW.put("item/stone_sword", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/stone_sword\"}}");
        RAW.put("item/string", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/string\"}}");
        RAW.put("item/sugar", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/sugar\"}}");
        RAW.put("item/sunflower", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_sunflower_front\"}}");
        RAW.put("item/tall_fern", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_fern_top\"}}");
        RAW.put("item/tall_grass", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/double_plant_grass_top\"}}");
        RAW.put("item/tnt_minecart", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/minecart_tnt\"}}");
        RAW.put("item/torch", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/torch_on\"}}");
        RAW.put("item/trip_wire_hook", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/trip_wire_source\"}}");
        RAW.put("item/tripwire_hook", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/trip_wire_source\"}}");
        RAW.put("item/tulip_orange", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_tulip_orange\"}}");
        RAW.put("item/tulip_pink", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_tulip_pink\"}}");
        RAW.put("item/tulip_red", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_tulip_red\"}}");
        RAW.put("item/tulip_white", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/flower_tulip_white\"}}");
        RAW.put("item/water_bucket", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/bucket_water\"}}");
        RAW.put("item/web", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/web\"}}");
        RAW.put("item/wheat", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/wheat\"}}");
        RAW.put("item/wheat_seeds", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/seeds_wheat\"}}");
        RAW.put("item/white_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_white\"}}");
        RAW.put("item/wither_head", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:items/skull_wither\"}}");
        RAW.put("item/wooden_axe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/wood_axe\"}}");
        RAW.put("item/wooden_door", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/door_wood\"}}");
        RAW.put("item/wooden_hoe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/wood_hoe\"}}");
        RAW.put("item/wooden_pickaxe", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/wood_pickaxe\"}}");
        RAW.put("item/wooden_shovel", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/wood_shovel\"}}");
        RAW.put("item/wooden_sword", "{\"parent\":\"item/handheld\",\"textures\":{\"layer0\":\"minecraft:items/wood_sword\"}}");
        RAW.put("item/writable_book", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/book_writable\"}}");
        RAW.put("item/written_book", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:items/book_written\"}}");
        RAW.put("item/yellow_stained_glass_pane", "{\"parent\":\"item/generated\",\"textures\":{\"layer0\":\"minecraft:blocks/glass_yellow\"}}");
        RAW.put("item/zombie_head", "{\"parent\":\"minecraft:item/generated\",\"textures\":{\"layer0\":\"minecraft:items/skull_zombie\"}}");

    }

    /**
     * Parse the raw table into JSON trees.
     *
     * @return key to parsed JSON (fresh map per call)
     */
    public static Map<String, JsonElement> load() {
        Map<String, JsonElement> out = new LinkedHashMap<String, JsonElement>();
        for (Map.Entry<String, String> e : RAW.entrySet()) {
            out.put(e.getKey(), new JsonParser().parse(e.getValue()));
        }
        return out;
    }

    /**
     * @return all keys of this table
     */
    public static java.util.Set<String> keys() {
        return RAW.keySet();
    }

    private ModelItemRawData() {
    }
}
