package decok.dfcdvadstf.catframe.datagen.migration;

import decok.dfcdvadstf.catframe.datagen.blockstate.BlockStateBuilders;
import decok.dfcdvadstf.catframe.model.state.BlockstateJson;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Auto-generated by .qoder/extract_datagen.py - do not edit.
 * <p>
 * Blockstate preset rules: each entry routes one hand-written
 * blockstate through a BlockStateBuilders preset. Only structures whose
 * variant key matrix exactly matches the preset are listed here;
 * everything else lives in BlockstateRawData.
 * <p>
 * 由 .qoder/extract_datagen.py 自动生成：blockstate 预设规则表。
 * 键矩阵与预设精确一致的条目在此路由到预设构建器，其余在数据表中。
 */
public final class BlockstateRules {

    private static final Map<String, BlockstateJson> RULES = new LinkedHashMap<String, BlockstateJson>();

    static {
        RULES.put("acacia_stairs", BlockStateBuilders.stairs("minecraft:block/acacia_stairs", "minecraft:block/acacia_inner_stairs", "minecraft:block/acacia_outer_stairs"));
        RULES.put("anvil", BlockStateBuilders.anvil(new String[]{"minecraft:block/anvil_intact", "minecraft:block/anvil_slightly_damaged", "minecraft:block/anvil_very_damaged"}));
        RULES.put("beacon", BlockStateBuilders.simple("minecraft:block/beacon"));
        RULES.put("bedrock", BlockStateBuilders.simple("minecraft:block/bedrock"));
        RULES.put("birch_stairs", BlockStateBuilders.stairs("minecraft:block/birch_stairs", "minecraft:block/birch_inner_stairs", "minecraft:block/birch_outer_stairs"));
        RULES.put("bookshelf", BlockStateBuilders.simple("minecraft:block/bookshelf"));
        RULES.put("brick_block", BlockStateBuilders.simple("minecraft:block/brick_block"));
        RULES.put("brick_stairs", BlockStateBuilders.stairs("minecraft:block/brick_stairs", "minecraft:block/brick_inner_stairs", "minecraft:block/brick_outer_stairs"));
        RULES.put("cactus", BlockStateBuilders.simple("minecraft:block/cactus"));
        RULES.put("cake", BlockStateBuilders.cake("minecraft:block/cake"));
        RULES.put("carrots", BlockStateBuilders.cropStages(new String[]{"minecraft:block/carrot_stage0", "minecraft:block/carrot_stage0", "minecraft:block/carrot_stage1", "minecraft:block/carrot_stage1", "minecraft:block/carrot_stage2", "minecraft:block/carrot_stage2", "minecraft:block/carrot_stage3", "minecraft:block/carrot_stage3"}));
        RULES.put("cauldron", BlockStateBuilders.cauldron(new String[]{"minecraft:block/cauldron_empty", "minecraft:block/cauldron_level1", "minecraft:block/cauldron_level2", "minecraft:block/cauldron_full"}));
        RULES.put("clay", BlockStateBuilders.simple("minecraft:block/clay"));
        RULES.put("coal_block", BlockStateBuilders.simple("minecraft:block/coal_block"));
        RULES.put("coal_ore", BlockStateBuilders.simple("minecraft:block/coal_ore"));
        RULES.put("cobblestone", BlockStateBuilders.simple("minecraft:block/cobblestone"));
        RULES.put("command_block", BlockStateBuilders.simple("minecraft:block/command_block"));
        RULES.put("crafting_table", BlockStateBuilders.simple("minecraft:block/crafting_table"));
        RULES.put("dark_oak_stairs", BlockStateBuilders.stairs("minecraft:block/dark_oak_stairs", "minecraft:block/dark_oak_inner_stairs", "minecraft:block/dark_oak_outer_stairs"));
        RULES.put("dead_bush", BlockStateBuilders.simple("minecraft:block/deadbush"));
        RULES.put("diamond_block", BlockStateBuilders.simple("minecraft:block/diamond_block"));
        RULES.put("diamond_ore", BlockStateBuilders.simple("minecraft:block/diamond_ore"));
        RULES.put("dispenser", BlockStateBuilders.dispenser("minecraft:block/dispenser_vertical", "minecraft:block/dispenser"));
        RULES.put("double_plant", BlockStateBuilders.doublePlant(map2("double_fern", "minecraft:block/double_fern_bottom", "minecraft:block/double_fern_top", "double_grass", "minecraft:block/tall_grass_bottom", "minecraft:block/tall_grass_top", "lilac", "minecraft:block/lilac_bottom", "minecraft:block/lilac_top", "peony", "minecraft:block/peony_bottom", "minecraft:block/peony_top", "rose_bush", "minecraft:block/rose_bush_bottom", "minecraft:block/rose_bush_top", "sunflower", "minecraft:block/sunflower_bottom", "minecraft:block/sunflower_top")));
        RULES.put("dropper", BlockStateBuilders.dispenser("minecraft:block/dropper_vertical", "minecraft:block/dropper"));
        RULES.put("emerald_block", BlockStateBuilders.simple("minecraft:block/emerald_block"));
        RULES.put("emerald_ore", BlockStateBuilders.simple("minecraft:block/emerald_ore"));
        RULES.put("end_stone", BlockStateBuilders.simple("minecraft:block/end_stone"));
        RULES.put("fence_gate", BlockStateBuilders.gate("minecraft:block/oak_fence_gate", "minecraft:block/oak_fence_gate_open"));
        RULES.put("furnace", BlockStateBuilders.facing4North("minecraft:block/furnace"));
        RULES.put("glass", BlockStateBuilders.simple("minecraft:block/glass"));
        RULES.put("glowstone", BlockStateBuilders.simple("minecraft:block/glowstone"));
        RULES.put("gold_block", BlockStateBuilders.simple("minecraft:block/gold_block"));
        RULES.put("gold_ore", BlockStateBuilders.simple("minecraft:block/gold_ore"));
        RULES.put("gravel", BlockStateBuilders.simple("minecraft:block/gravel"));
        RULES.put("hardened_clay", BlockStateBuilders.simple("minecraft:block/hardened_clay"));
        RULES.put("hay_block", BlockStateBuilders.simple("minecraft:block/hay_block"));
        RULES.put("hopper", BlockStateBuilders.hopper("minecraft:block/hopper", "minecraft:block/hopper_side"));
        RULES.put("ice", BlockStateBuilders.simple("minecraft:block/ice"));
        RULES.put("iron_block", BlockStateBuilders.simple("minecraft:block/iron_block"));
        RULES.put("iron_door", BlockStateBuilders.door("minecraft:block/iron_door"));
        RULES.put("iron_ore", BlockStateBuilders.simple("minecraft:block/iron_ore"));
        RULES.put("jukebox", BlockStateBuilders.simple("minecraft:block/jukebox"));
        RULES.put("jungle_stairs", BlockStateBuilders.stairs("minecraft:block/jungle_stairs", "minecraft:block/jungle_inner_stairs", "minecraft:block/jungle_outer_stairs"));
        RULES.put("ladder", BlockStateBuilders.facing4("minecraft:block/ladder"));
        RULES.put("lapis_block", BlockStateBuilders.simple("minecraft:block/lapis_block"));
        RULES.put("lapis_ore", BlockStateBuilders.simple("minecraft:block/lapis_ore"));
        RULES.put("lever", BlockStateBuilders.lever("minecraft:block/lever_wall", "minecraft:block/lever_wall_on", "minecraft:block/lever", "minecraft:block/lever_on"));
        RULES.put("lit_furnace", BlockStateBuilders.facing4North("minecraft:block/lit_furnace"));
        RULES.put("lit_pumpkin", BlockStateBuilders.facing4("minecraft:block/jack_o_lantern"));
        RULES.put("lit_redstone_lamp", BlockStateBuilders.simple("minecraft:block/redstone_lamp_on"));
        RULES.put("lit_redstone_ore", BlockStateBuilders.simple("minecraft:block/redstone_ore"));
        RULES.put("log", BlockStateBuilders.logs(map("birch", "minecraft:block/birch_log", "jungle", "minecraft:block/jungle_log", "oak", "minecraft:block/oak_log", "spruce", "minecraft:block/spruce_log")));
        RULES.put("log2", BlockStateBuilders.logs(map("acacia", "minecraft:block/acacia_log", "dark_oak", "minecraft:block/dark_oak_log")));
        RULES.put("melon_block", BlockStateBuilders.simple("minecraft:block/melon_block"));
        RULES.put("melon_stem", BlockStateBuilders.cropStages(new String[]{"minecraft:block/melon_stem_stage0", "minecraft:block/melon_stem_stage1", "minecraft:block/melon_stem_stage2", "minecraft:block/melon_stem_stage3", "minecraft:block/melon_stem_stage4", "minecraft:block/melon_stem_stage5", "minecraft:block/melon_stem_stage6", "minecraft:block/melon_stem_stage7"}));
        RULES.put("mossy_cobblestone", BlockStateBuilders.simple("minecraft:block/mossy_cobblestone"));
        RULES.put("mycelium", BlockStateBuilders.simple("minecraft:block/mycelium"));
        RULES.put("nether_brick", BlockStateBuilders.simple("minecraft:block/nether_brick"));
        RULES.put("nether_brick_stairs", BlockStateBuilders.stairs("minecraft:block/nether_brick_stairs", "minecraft:block/nether_brick_inner_stairs", "minecraft:block/nether_brick_outer_stairs"));
        RULES.put("netherrack", BlockStateBuilders.simple("minecraft:block/netherrack"));
        RULES.put("noteblock", BlockStateBuilders.simple("minecraft:block/noteblock"));
        RULES.put("oak_stairs", BlockStateBuilders.stairs("minecraft:block/oak_stairs", "minecraft:block/oak_inner_stairs", "minecraft:block/oak_outer_stairs"));
        RULES.put("obsidian", BlockStateBuilders.simple("minecraft:block/obsidian"));
        RULES.put("packed_ice", BlockStateBuilders.simple("minecraft:block/packed_ice"));
        RULES.put("piston", BlockStateBuilders.piston("minecraft:block/piston", "minecraft:block/piston_extended"));
        RULES.put("piston_head", BlockStateBuilders.pistonHead("minecraft:block/piston_head", "minecraft:block/piston_head_sticky"));
        RULES.put("potatoes", BlockStateBuilders.cropStages(new String[]{"minecraft:block/potato_stage0", "minecraft:block/potato_stage0", "minecraft:block/potato_stage1", "minecraft:block/potato_stage1", "minecraft:block/potato_stage2", "minecraft:block/potato_stage2", "minecraft:block/potato_stage3", "minecraft:block/potato_stage3"}));
        RULES.put("powered_comparator", BlockStateBuilders.comparator("minecraft:block/comparator"));
        RULES.put("powered_repeater", BlockStateBuilders.repeater("minecraft:block/repeater", "_on"));
        RULES.put("pumpkin", BlockStateBuilders.facing4("minecraft:block/pumpkin"));
        RULES.put("pumpkin_stem", BlockStateBuilders.cropStages(new String[]{"minecraft:block/pumpkin_stem_stage0", "minecraft:block/pumpkin_stem_stage1", "minecraft:block/pumpkin_stem_stage2", "minecraft:block/pumpkin_stem_stage3", "minecraft:block/pumpkin_stem_stage4", "minecraft:block/pumpkin_stem_stage5", "minecraft:block/pumpkin_stem_stage6", "minecraft:block/pumpkin_stem_stage7"}));
        RULES.put("quartz_ore", BlockStateBuilders.simple("minecraft:block/quartz_ore"));
        RULES.put("quartz_stairs", BlockStateBuilders.stairs("minecraft:block/quartz_stairs", "minecraft:block/quartz_inner_stairs", "minecraft:block/quartz_outer_stairs"));
        RULES.put("redstone_block", BlockStateBuilders.simple("minecraft:block/redstone_block"));
        RULES.put("redstone_lamp", BlockStateBuilders.simple("minecraft:block/redstone_lamp"));
        RULES.put("redstone_ore", BlockStateBuilders.simple("minecraft:block/redstone_ore"));
        RULES.put("redstone_torch", BlockStateBuilders.torch("minecraft:block/redstone_torch", "minecraft:block/redstone_torch_wall"));
        RULES.put("reeds", BlockStateBuilders.reeds("minecraft:block/reeds"));
        RULES.put("sandstone_stairs", BlockStateBuilders.stairs("minecraft:block/sandstone_stairs", "minecraft:block/sandstone_inner_stairs", "minecraft:block/sandstone_outer_stairs"));
        RULES.put("snow", BlockStateBuilders.simple("minecraft:block/snow"));
        RULES.put("soul_sand", BlockStateBuilders.simple("minecraft:block/soul_sand"));
        RULES.put("sponge", BlockStateBuilders.simple("minecraft:block/sponge"));
        RULES.put("spruce_stairs", BlockStateBuilders.stairs("minecraft:block/spruce_stairs", "minecraft:block/spruce_inner_stairs", "minecraft:block/spruce_outer_stairs"));
        RULES.put("sticky_piston", BlockStateBuilders.piston("minecraft:block/sticky_piston", "minecraft:block/sticky_piston_extended"));
        RULES.put("stone", BlockStateBuilders.simple("minecraft:block/stone"));
        RULES.put("stone_brick_stairs", BlockStateBuilders.stairs("minecraft:block/stone_brick_stairs", "minecraft:block/stone_brick_inner_stairs", "minecraft:block/stone_brick_outer_stairs"));
        RULES.put("stone_button", BlockStateBuilders.button("minecraft:block/stone_button", "minecraft:block/stone_button_pressed"));
        RULES.put("stone_slab", BlockStateBuilders.slabByVariant(map2("brick", "minecraft:block/slab_brick", "minecraft:block/slab_brick_top", "cobblestone", "minecraft:block/slab_cobblestone", "minecraft:block/slab_cobblestone_top", "nether_brick", "minecraft:block/slab_nether_brick", "minecraft:block/slab_nether_brick_top", "quartz", "minecraft:block/slab_quartz", "minecraft:block/slab_quartz_top", "sandstone", "minecraft:block/slab_sandstone", "minecraft:block/slab_sandstone_top", "stone", "minecraft:block/slab_stone", "minecraft:block/slab_stone_top", "stone_brick", "minecraft:block/slab_stone_brick", "minecraft:block/slab_stone_brick_top", "wood", "minecraft:block/slab_wood", "minecraft:block/slab_wood_top")));
        RULES.put("stone_stairs", BlockStateBuilders.stairs("minecraft:block/cobblestone_stairs", "minecraft:block/cobblestone_inner_stairs", "minecraft:block/cobblestone_outer_stairs"));
        RULES.put("tnt", BlockStateBuilders.simple("minecraft:block/tnt"));
        RULES.put("torch", BlockStateBuilders.torch("minecraft:block/torch", "minecraft:block/torch_wall"));
        RULES.put("trapdoor", BlockStateBuilders.trapdoor("minecraft:block/trapdoor_bottom", "minecraft:block/trapdoor_top", "minecraft:block/trapdoor_open"));
        RULES.put("unlit_redstone_torch", BlockStateBuilders.torch("minecraft:block/redstone_torch_off", "minecraft:block/redstone_torch_wall_off"));
        RULES.put("unpowered_comparator", BlockStateBuilders.comparator("minecraft:block/comparator"));
        RULES.put("unpowered_repeater", BlockStateBuilders.repeater("minecraft:block/repeater", ""));
        RULES.put("wheat", BlockStateBuilders.cropStages(new String[]{"minecraft:block/wheat_stage0", "minecraft:block/wheat_stage1", "minecraft:block/wheat_stage2", "minecraft:block/wheat_stage3", "minecraft:block/wheat_stage4", "minecraft:block/wheat_stage5", "minecraft:block/wheat_stage6", "minecraft:block/wheat_stage7"}));
        RULES.put("wooden_button", BlockStateBuilders.button("minecraft:block/wood_button", "minecraft:block/wood_button_pressed"));
        RULES.put("wooden_door", BlockStateBuilders.door("minecraft:block/wooden_door"));

    }

    /**
     * @return copy of the rule table (name to built blockstate)
     */
    public static Map<String, BlockstateJson> all() {
        return new LinkedHashMap<String, BlockstateJson>(RULES);
    }

    private static Map<String, String> map(String... kv) {
        Map<String, String> m = new LinkedHashMap<String, String>();
        for (int i = 0; i < kv.length; i += 2) {
            m.put(kv[i], kv[i + 1]);
        }
        return m;
    }

    private static Map<String, String[]> map2(String... kv) {
        Map<String, String[]> m = new LinkedHashMap<String, String[]>();
        for (int i = 0; i < kv.length; i += 3) {
            m.put(kv[i], new String[]{kv[i + 1], kv[i + 2]});
        }
        return m;
    }

    private BlockstateRules() {
    }
}
