package decok.dfcdvadstf.catframe.datagen.migration;

import com.google.gson.JsonObject;
import decok.dfcdvadstf.catframe.datagen.tag.TagBuilder;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Auto-generated by .qoder/extract_datagen.py - do not edit.
 * <p>
 * CatFrame tag tables: each entry is one tag's value list, built
 * through TagBuilder ({"replace": false, "values": [...]}).
 * <p>
 * 由 .qoder/extract_datagen.py 自动生成：catframe tag 值表。
 */
public final class TagRules {

    private static final Map<String, JsonObject> RULES = new LinkedHashMap<String, JsonObject>();

    static {
        RULES.put("blocks/beacon_base_blocks", TagBuilder.tag(false, "minecraft:iron_block", "minecraft:gold_block", "minecraft:diamond_block", "minecraft:emerald_block"));
        RULES.put("blocks/can_glide_through", TagBuilder.tag(false, "minecraft:air", "minecraft:water", "minecraft:flowing_water", "minecraft:lava", "minecraft:flowing_lava", "minecraft:fire", "minecraft:torch", "minecraft:redstone_wire", "minecraft:tallgrass", "minecraft:deadbush", "minecraft:yellow_flower", "minecraft:red_flower", "minecraft:brown_mushroom", "minecraft:red_mushroom", "minecraft:snow_layer", "minecraft:wheat", "minecraft:carrots", "minecraft:potatoes", "minecraft:reeds", "minecraft:web", "minecraft:vine", "minecraft:ladder", "minecraft:sign", "minecraft:wall_sign", "minecraft:rail", "minecraft:golden_rail", "minecraft:detector_rail", "minecraft:activator_rail", "minecraft:lever", "minecraft:stone_button", "minecraft:wooden_button", "minecraft:tripwire_hook", "minecraft:tripwire", "minecraft:carpet"));
        RULES.put("blocks/climbable", TagBuilder.tag(false, "minecraft:ladder", "minecraft:vine"));
        RULES.put("blocks/dampens_vibrations", TagBuilder.tag(false, "#catframe:wool"));
        RULES.put("blocks/glass", TagBuilder.tag(false, "minecraft:glass", "minecraft:stained_glass", "minecraft:glass_pane", "minecraft:stained_glass_pane"));
        RULES.put("blocks/logs", TagBuilder.tag(false, "minecraft:log", "minecraft:log2"));
        RULES.put("blocks/mineable/axe", TagBuilder.tag(false, "minecraft:planks", "minecraft:log", "minecraft:log2", "minecraft:bookshelf", "minecraft:chest", "minecraft:trapped_chest", "minecraft:crafting_table", "minecraft:fence", "minecraft:fence_gate", "minecraft:wooden_door", "minecraft:trapdoor", "minecraft:wooden_pressure_plate", "minecraft:wooden_button", "minecraft:noteblock", "minecraft:jukebox", "minecraft:ladder", "minecraft:sign", "minecraft:wall_sign", "minecraft:wooden_slab", "minecraft:double_wooden_slab", "minecraft:daylight_detector", "minecraft:melon_block", "minecraft:pumpkin", "minecraft:lit_pumpkin", "minecraft:cocoa"));
        RULES.put("blocks/mineable/hoe", TagBuilder.tag(false, "minecraft:leaves", "minecraft:leaves2", "minecraft:sponge", "minecraft:hay_block"));
        RULES.put("blocks/mineable/pickaxe", TagBuilder.tag(false, "minecraft:stone", "minecraft:cobblestone", "minecraft:mossy_cobblestone", "minecraft:stonebrick", "minecraft:stone_slab", "minecraft:double_stone_slab", "minecraft:brick_block", "minecraft:sandstone", "minecraft:nether_brick", "minecraft:quartz_block", "minecraft:quartz_ore", "minecraft:netherrack", "minecraft:end_stone", "minecraft:coal_ore", "minecraft:iron_ore", "minecraft:gold_ore", "minecraft:diamond_ore", "minecraft:emerald_ore", "minecraft:redstone_ore", "minecraft:lapis_ore", "minecraft:iron_block", "minecraft:gold_block", "minecraft:diamond_block", "minecraft:emerald_block", "minecraft:coal_block", "minecraft:lapis_block", "minecraft:redstone_block", "minecraft:quartz_block", "minecraft:obsidian", "minecraft:furnace", "minecraft:lit_furnace", "minecraft:dispenser", "minecraft:dropper", "minecraft:hopper", "minecraft:piston", "minecraft:sticky_piston", "minecraft:anvil", "minecraft:enchanting_table", "minecraft:brewing_stand", "minecraft:cauldron", "minecraft:beacon", "minecraft:iron_bars", "minecraft:stone_pressure_plate", "minecraft:stone_button", "minecraft:rail", "minecraft:golden_rail", "minecraft:detector_rail", "minecraft:activator_rail", "minecraft:heavy_weighted_pressure_plate", "minecraft:light_weighted_pressure_plate", "minecraft:command_block", "minecraft:mob_spawner", "minecraft:ender_chest"));
        RULES.put("blocks/mineable/shovel", TagBuilder.tag(false, "minecraft:dirt", "minecraft:grass", "minecraft:sand", "minecraft:gravel", "minecraft:clay", "minecraft:soul_sand", "minecraft:mycelium", "minecraft:snow", "minecraft:snow_layer", "minecraft:farmland"));
        RULES.put("blocks/needs_diamond_tool", TagBuilder.tag(false, "minecraft:obsidian"));
        RULES.put("blocks/needs_iron_tool", TagBuilder.tag(false, "minecraft:diamond_ore", "minecraft:emerald_ore", "minecraft:diamond_block", "minecraft:emerald_block", "minecraft:gold_block", "minecraft:gold_ore"));
        RULES.put("blocks/needs_stone_tool", TagBuilder.tag(false, "minecraft:iron_ore", "minecraft:gold_ore", "minecraft:iron_block", "minecraft:gold_block", "minecraft:lapis_ore", "minecraft:lapis_block", "minecraft:redstone_ore", "minecraft:redstone_block"));
        RULES.put("blocks/planks", TagBuilder.tag(false, "minecraft:planks", "minecraft:wooden_slab", "minecraft:double_wooden_slab"));
        RULES.put("blocks/prevents_leaf_decay", TagBuilder.tag(false, "#catframe:logs"));
        RULES.put("blocks/stones", TagBuilder.tag(false, "minecraft:stone", "minecraft:cobblestone", "minecraft:mossy_cobblestone", "minecraft:stonebrick", "minecraft:stone_slab", "minecraft:double_stone_slab", "minecraft:sandstone", "minecraft:nether_brick", "minecraft:quartz_block", "minecraft:brick_block"));
        RULES.put("blocks/wool", TagBuilder.tag(false, "minecraft:wool"));
        RULES.put("items/axes", TagBuilder.tag(false, "minecraft:wooden_axe", "minecraft:stone_axe", "minecraft:iron_axe", "minecraft:golden_axe", "minecraft:diamond_axe"));
        RULES.put("items/brewing_items", TagBuilder.tag(false, "minecraft:nether_wart", "minecraft:blaze_powder", "minecraft:fermented_spider_eye", "minecraft:ghast_tear", "minecraft:glistering_melon", "minecraft:magma_cream", "minecraft:sugar", "minecraft:spider_eye", "minecraft:gunpowder", "minecraft:redstone", "minecraft:glowstone_dust"));
        RULES.put("items/dyes", TagBuilder.tag(false, "minecraft:dye"));
        RULES.put("items/foods", TagBuilder.tag(false, "minecraft:apple", "minecraft:bread", "minecraft:cooked_porkchop", "minecraft:porkchop", "minecraft:cooked_beef", "minecraft:beef", "minecraft:cooked_chicken", "minecraft:chicken", "minecraft:cooked_fished", "minecraft:fish", "minecraft:cookie", "minecraft:melon", "minecraft:carrot", "minecraft:potato", "minecraft:baked_potato", "minecraft:poisonous_potato", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:pumpkin_pie", "minecraft:golden_apple", "minecraft:golden_carrot", "minecraft:cake"));
        RULES.put("items/fuels", TagBuilder.tag(false, "minecraft:coal", "minecraft:blaze_rod", "#catframe:planks", "#catframe:logs"));
        RULES.put("items/hoes", TagBuilder.tag(false, "minecraft:wooden_hoe", "minecraft:stone_hoe", "minecraft:iron_hoe", "minecraft:golden_hoe", "minecraft:diamond_hoe"));
        RULES.put("items/logs", TagBuilder.tag(false, "minecraft:log", "minecraft:log2"));
        RULES.put("items/pickaxes", TagBuilder.tag(false, "minecraft:wooden_pickaxe", "minecraft:stone_pickaxe", "minecraft:iron_pickaxe", "minecraft:golden_pickaxe", "minecraft:diamond_pickaxe"));
        RULES.put("items/planks", TagBuilder.tag(false, "minecraft:planks", "minecraft:wooden_slab"));
        RULES.put("items/shovels", TagBuilder.tag(false, "minecraft:wooden_shovel", "minecraft:stone_shovel", "minecraft:iron_shovel", "minecraft:golden_shovel", "minecraft:diamond_shovel"));
        RULES.put("items/stones", TagBuilder.tag(false, "minecraft:stone", "minecraft:cobblestone", "minecraft:mossy_cobblestone", "minecraft:stonebrick", "minecraft:stone_slab", "minecraft:sandstone", "minecraft:nether_brick", "minecraft:quartz_block", "minecraft:brick_block"));
        RULES.put("items/swords", TagBuilder.tag(false, "minecraft:wooden_sword", "minecraft:stone_sword", "minecraft:iron_sword", "minecraft:golden_sword", "minecraft:diamond_sword"));
        RULES.put("items/tools", TagBuilder.tag(false, "#catframe:swords", "#catframe:axes", "#catframe:pickaxes", "#catframe:shovels", "#catframe:hoes", "minecraft:shears", "minecraft:flint_and_steel", "minecraft:compass", "minecraft:clock", "minecraft:fishing_rod"));
        RULES.put("items/wool", TagBuilder.tag(false, "minecraft:wool", "minecraft:carpet"));

    }

    /**
     * @return copy of the tag rule table (name to JSON tree)
     */
    public static Map<String, JsonObject> all() {
        return new LinkedHashMap<String, JsonObject>(RULES);
    }

    private TagRules() {
    }
}
